### ISSUE TITLE
Раздел ExperimentalFilter

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardTeam.github.io#1]
Не желаете переименовать раздел ExperimentalFilter?
Там экспериментального по сути уже ничего нет, это уже ads tracker

**Comment by ameshkov** [comment]
Ссылки старые поломаются, в остальном было бы неплохо.

Заодно и разработку основных фильтров туда же утащить.
А то фильтры ж открытые, чего их разработку держать непонятно где.

**Comment by ameshkov** [comment]
Хотяя, говорят редиректы будут со старых ссылок:
https://help.github.com/articles/renaming-a-repository/

**Comment by Embos** [comment]
Ссылки поломаются? Ну они же кажется нигде так активно не используются, как например ссылки на задачи по исправлению багов, да и тем более редирект.
Основные фильтры перенести? То есть можно будет смотреть изменения и прочее что касается фильтров? Хм, здорово)

**Comment by a-ladanov** [comment]
Задача выполнена
#closed

**Comment by ameshkov** [comment]
И действительно:)
