### ISSUE TITLE
Adguard for Windows 6.3.1374.4023-rc

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardTeam.github.io#2]
Не наблюдаю ссылку на загрузку новой версии на странице
https://github.com/AdguardTeam/AdguardForWindows/releases/tag/v6.3.1374.4023-rc

**Comment by vozersky** [comment]
вероятно, версию не сразу загрузили в пост, сейчас все на месте

![image](https://user-images.githubusercontent.com/17472907/42273170-1a4d4b34-7f91-11e8-9d5a-03e423ab0b0a.png)
