### ISSUE TITLE
Using the same IP address as your VPN service

### ISSUE THREAD

**Issue by FsAguard62** [AdguardTeam/AdguardTeam.github.io#3]
There are, three-domain websites using the same IP addresses! I think maybe you guys should look into this! 

Domain: extension-outlook.mojilala.com
Domain: gracevictoria.space
The IP address is A, 172.64.80.1 
And the other one is: 
Domain: whoami.adguard-vpn.online
Domain: veryawesomeprivacy.org
Domain: api.adguard.io

**Comment by vozersky** [comment]
@FsAguard62 This is an IP address of [Cloudflare](https://www.cloudflare.com/), it's perfectly normal.

**Comment by FsAguard62** [comment]
Okay, I well appreciate the reply from you, and thank you so much, mate.
